name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
jobs:
  test-asfaload:
    runs-on: ubuntu-latest
    #permissions:
    #  id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: test install
        uses: ./
      - run: |
          asfald https://github.com/superfly/flyctl/releases/download/v0.3.48/flyctl_0.3.48_Linux_x86_64.tar.gz
